# Generated by Django 5.0.3 on 2026-10-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_team_gamescore_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.CharField(default='nhl', max_length=10),
        ),
    ]
