# Generated by Django 5.0.3 on 2026-10-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_team_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default='DAL', max_length=10),
        ),
    ]
