services:
  web:
    image: ghcr.io/bryangerlach/sportsticker:latest
    ports:
      - "5555:5555"
    volumes:
      - ./db:/app/db
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=your-production-super-secret-key-here
      - CSRF_TRUSTED_ORIGINS=https://yourdomain.com,http://localhost:8000
      - DEBUG=True
    restart: unless-stopped